//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTable
    {
        public string CT_type { get; set; }
        public string CT_typedesc { get; set; }
        public string CT_value { get; set; }
        public string CT_desc { get; set; }
        public string CT_relationtype { get; set; }
        public string CT_relationvalue { get; set; }
        public Nullable<int> CT_order { get; set; }
        public Nullable<bool> CT_enabled { get; set; }
        public string CT_mod_user { get; set; }
        public string CT_mod_date { get; set; }
        public string CT_remark { get; set; }
    }
}
