//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeFile
    {
        public int kf_id { get; set; }
        public string kf_name { get; set; }
        public string kf_creator { get; set; }
        public Nullable<System.DateTime> kf_create_date { get; set; }
        public string kf_modifier { get; set; }
        public Nullable<System.DateTime> kf_modified_date { get; set; }
        public int kf_k_id { get; set; }
    }
}
