//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knowledge
    {
        public int k_id { get; set; }
        public int k_type { get; set; }
        public string k_title { get; set; }
        public string k_content { get; set; }
        public string k_picture { get; set; }
        public Nullable<System.DateTime> k_start_date { get; set; }
        public Nullable<System.DateTime> k_end_date { get; set; }
        public bool k_is_public { get; set; }
        public string k_creator { get; set; }
        public Nullable<System.DateTime> k_create_date { get; set; }
        public string k_modifier { get; set; }
        public Nullable<System.DateTime> k_modified_date { get; set; }
        public string k_brief { get; set; }
    }
}
