//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long l_id { get; set; }
        public string l_level { get; set; }
        public string l_Method { get; set; }
        public string l_url { get; set; }
        public string l_message { get; set; }
        public string l_ip { get; set; }
        public string l_account { get; set; }
        public Nullable<System.DateTime> l_create_date { get; set; }
    }
}
