//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int n_id { get; set; }
        public int n_type { get; set; }
        public string n_title { get; set; }
        public string n_content { get; set; }
        public string n_picture { get; set; }
        public Nullable<System.DateTime> n_start_date { get; set; }
        public Nullable<System.DateTime> n_end_date { get; set; }
        public bool n_is_public { get; set; }
        public string n_creator { get; set; }
        public Nullable<System.DateTime> n_create_date { get; set; }
        public string n_modifier { get; set; }
        public Nullable<System.DateTime> n_modified_date { get; set; }
        public string n_brief { get; set; }
        public string n_url { get; set; }
        public string n_parent_type { get; set; }
    }
}
