//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int u_id { get; set; }
        public int u_type { get; set; }
        public string u_account { get; set; }
        public string u_password { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string u_creator { get; set; }
        public Nullable<System.DateTime> u_create_date { get; set; }
        public string u_modifier { get; set; }
        public Nullable<System.DateTime> u_modified_date { get; set; }
    }
}
